config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :rooms
    resources :users
    resource :user_sessions, only: [:new, :create, :destroy]
  end

  resource :confirmation, only: [:show]

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates_presence_of :title, :location, :description
  validates_length_of :description, minimum: 20

  def complete_name
    "#{title}, #{location}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  #scope :most_recent, -> { order('created_at DESC')}
  #scope :from_sampa, -> { where(location: "São Paulo")}
  #scope :de, -> (location) { where(location: location)}
  #default_scope -> { where('confirmed_at IS NOT NULL')}

  scope :confirmed, -> {where.not(confirmed_at: nil)}

  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\Z/

  validates_presence_of :email, :full_name, :location
  validates_length_of :bio, in: 10..30, allow_blank: false
  validates_uniqueness_of :email
  validates_format_of :email, with: EMAIL_REGEXP

  has_secure_password

  before_create do |user|
    user.confirmation_token = SecureRandom.urlsafe_base64
  end

  def confirm!
    return if confirmed?

    self.confirmed_at = Time.current
    self.confirmation_token = ''
    save!
  end

  def confirmed?
    confirmed_at.present?
  end

  def self.authenticate(email, password)
    #user = confirmed.find_by(email: email)
    #if user.present?
    #  user.authenticate(password)
    #end
    user = confirmed.find_by(email: email).try(:authenticate, password)
  end

  #private
  #def email_format
  #  errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
  #end
end

app/models/user_session.rb
class UserSession
  include ActiveModel::Model

  attr_accessor :email, :password
  validates_presence_of :email, :password

  def initialize(session, attributes={})
    @session = session
    @email = attributes[:email]
    @password = attributes[:password]
  end

  def authenticate!
    user = User.authenticate(@email, @password)

    if user.present?
      store(user)
    else
      errors.add(:base, :invalid_login)
      false
    end
  end

  def store(user)
    @session[:user_id] = user.id
  end

  def current_user
    User.find(@session[:user_id])
  end

  def user_signed_in?
    @session[:user_id].present?
  end

  def destroy
    @session[:user_id] = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?

  protect_from_forgery with: :exception

  before_action do
    I18n.locale = params[:locale]
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def user_session
    UserSession.new(session)
  end

  def require_authentication
    unless user_signed_in?
      redirect_to new_user_sessions_path, alert: t('flash.alert.needs_login')
    end
  end

  def require_no_authentication
    if user_signed_in?
      redirect_to root_path, notice: t('flash.notice.already_logged_in')
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def show
    user = User.find_by(confirmation_token: params[:token])

    if user.present?
      user.confirm!
      redirect_to user, notice: I18n.t('confirmations.success')
    else
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.last(3)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to @room, notice: t('flash.notice.room_created')
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: t('flash.notice.room_updated')
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy

  def new
    @user_session = UserSession.new(session)
  end

  def create
    @user_session = UserSession.new(session, params[:user_session])

    if @user_session.authenticate!
      redirect_to root_path, notice: t('flash.notice.signed_in')
    else
      render :new
    end
  end

  def destroy
    user_session.destroy
    redirect_to root_path, notice: t('flash.notice.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    #cria um novo objeto com os parâmetros preenchidos
    @user = User.new(user_params)
    if @user.save
      Signup.confirm_email(@user).deliver_now
      redirect_to @user, notice: 'Cadastro criado com sucesso!'
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'Cadastro atualizado com sucesso!'
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :full_name, :location, :bio, :password, :password_confirmation)
  end

  def can_change
    unless user_signed_in? && current_user == user
      redirect_to user_path(params[:id])
    end
  end

  def user
    @user ||= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag(
          :div,
          model.errors[attribute].first,
          class: 'error_message'
      )
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1><%= t 'welcome.recent_rooms' %></h1>
  <ul>
    <% @rooms.each do |room| %>
      <li>
        <p><%= link_to room.complete_name , room, class: "btn btn-default"%></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_user_navbar.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to t('layout.new_room'), new_room_path %></li>
  <li><%= link_to t('layout.rooms'), rooms_path %></li>
  <li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
  <li>
    <a href="/pt/user_sessions" data-method="delete" rel="nofollow">
      Logout
    </a>
  </li>
</ul>

app/views/layouts/_visitor_navbar.html.erb
<ul class="nav navbar-nav">
  <li><%= link_to t('layout.rooms'), rooms_path %></li>
  <li><%= link_to t('layout.signup'), new_user_path %></li>
  <li>
    <%= link_to t('layout.signin'), new_user_sessions_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Colcho.net", root_path, class: "navbar-brand" %>
      </div>
      <% if user_signed_in? %>
        <%= render 'layouts/user_navbar' %>
      <% else %>
        <%= render 'layouts/visitor_navbar' %>
      <% end %>
    </div>
  </nav>
</header>

<div class="content">
  <% if notice.present? %>
    <p id="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
      <p id="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
    <% if @room.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <%= t 'general.form_error' %>
      </div>
    <% end %>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
      <%= error_tag @room, :title %>
    </p>

    <p>
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
      <%= error_tag @room, :location %>
    </p>
    <p>
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
      <%= error_tag @room, :description %>
    </p>

    <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/rooms/edit.html.erb
<h1><%= t '.title' %></h1>

<div id="content">
  <div id="form" class="section">
    <%= render 'form' %>
  </div>
</div>

<div align="center">
  <div class="btn-group" role="group" aria-label="Navigation">
    <%= link_to 'Ver', @room, class: 'btn btn-primary', role: 'button' %>
    <%= link_to 'Voltar', rooms_path, class: 'btn btn-primary btn-outline', role: 'button' %>
  </div>
</div>

app/views/rooms/index.html.erb
<h1 align="center">Lista de quartos</h1>

<div id="content">
  <div id="tabela" class="table-responsive">
    <table class="table-striped">
      <thead>
        <tr>
          <th><%= t 'rooms.title' %></th>
          <th><%= t 'rooms.location' %></th>
          <th><%= t 'rooms.description' %></th>
          <th colspan="10"></th>
        </tr>
      </thead>

      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.title %></td>
            <td><%= room.location %></td>
            <td><%= room.description %></td>
            <td>
              <div class="btn-group" role="group">
                <%= link_to t('layout.view'), room, class: 'btn btn-default btn-responsive' %>
                <%= link_to t('layout.editing'), edit_room_path(room), class: 'btn btn-default btn-responsive' %>
                <%= link_to t('layout.delete'), room, method: :delete, class: 'btn btn-danger btn-responsive', data: { confirm: 'Você tem certeza?' } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div align="center">
  <div class="btn-group" role="group">
    <%= link_to 'Novo quarto', new_room_path, class: 'btn btn-default', role: 'button' %>
    <%= link_to 'Home', root_path, class: 'btn btn-default', role: 'button' %>
  </div>
</div>

app/views/rooms/new.html.erb
<h1 align="center"><%= t '.title' %></h1>

<div id="content">
  <div id="form">
    <%= render 'form' %>
  </div>
</div>

<div align="center">
  <div class="btn-group" role="group">
    <%= link_to 'Voltar', rooms_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/rooms/show.html.erb
<div id="content">
  <p>
    <strong><%= t 'rooms.title' %></strong>
    <%= @room.title %>
  </p>

  <p>
    <strong><%= t 'rooms.location' %></strong>
    <%= @room.location %>
  </p>

  <p>
    <strong><%= t 'rooms.description' %></strong>
    <%= @room.description %>
  </p>
</div>

<div align="center">
  <div class="btn-group" role="group">
    <%= link_to 'Editar', edit_room_path(@room), class: 'btn btn-primary' %>
    <%= link_to 'Voltar', rooms_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %></h1>
<p>
  <%= t '.body', full_name: @user.full_name %>
</p>
<p>
  <%= t '.confirm_link_html', link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
  <%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.title' %>
<%= t '.body', full_name: @user.full_name %>
<%= t '.confirm_link_html', link: @confirmation_link %>

<%= t '.thanks_html', link: root_url %>

app/views/user_sessions/new.html.erb
<div align="center">
  <h1><%= t '.title' %></h1>

  <% if @user_session.errors.has_key? :base %>
      <div id="error_explanation">
        <%= @user_session.errors[:base].join(', ') %>
      </div>
  <% end %>

  <%= form_for @user_session do |f| %>
      <p>
        <%= f.text_field :email, class: "form-control", placeholder: t('activemodel.attributes.user_session.email') %>
        <%= error_tag @user_session, :email %>
      </p>

      <p>
        <%= f.password_field :password, class: "form-control", placeholder: t('activemodel.attributes.user_session.password') %>
        <%= error_tag @user_session, :password %>
      </p>

      <p>
        <%= f.submit class: "btn btn-default" %>
      </p>

      <p><%= link_to t('.sign_up'), new_user_path %></p>
  <% end %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <%= t 'general.form_error' %>
    </div>
<% end %>

<%= form_for @user do |f| %>
    <p>
      <%= f.text_field :full_name, class: "form-control", placeholder: t('activerecord.attributes.user.full_name') %>
      <%= error_tag @user, :full_name %>
    </p>

    <p>
      <%= f.text_field :location, class: "form-control", placeholder: t('activerecord.attributes.user.location') %>
      <%= error_tag @user, :location %>
    </p>

    <p>
      <%= f.text_field :email, class: "form-control", placeholder: t('activerecord.attributes.user.email') %>
      <%= error_tag @user, :email %>
    </p>

    <p>
      <%= f.password_field :password, class: "form-control", placeholder: t('activerecord.attributes.user.password') %>
      <%= error_tag @user, :password %>
    </p>

    <p>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: t('activerecord.attributes.user.password_confirmation')  %>
      <%= error_tag @user, :password_confirmation %>
    </p>

    <p>
      <%= f.text_area :bio, class: "form-control", placeholder: t('activerecord.attributes.user.bio') %>
      <%= error_tag @user, :bio %>
    </p>

  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<div id="content">
  <div id="form">
    <%= render 'form' %>
  </div>
</div>

<div align="center">
  <div class="btn-group" role="group">
    <%= link_to 'Voltar ao perfil', @user, class: 'btn btn-primary btn-responsive' %>
  </div>
</div>

app/views/users/new.html.erb
<h1 align="center"><%= t '.title' %></h1>

<div id="content">
  <div id="form" align="center">
    <%= render 'form' %>
  </div>
</div>

<div align="center">
  <div class="btn-group" role="group" aria-label="Navigation">
    <%= link_to 'Voltar', root_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/users/show.html.erb
<div id="content">
  <h1><%= t '.title', user_name: @user.full_name %></h1>

  <ul>
    <li><%= t '.location', location: @user.location %></li>
    <li><%= t '.bio', bio:  @user.bio %></li>
  </ul>
</div>

<div align="center">
  <div class="btn-group" role="group" aria-label="Navigation">
    <%= link_to 'Editar perfil', edit_user_path(@user), class: 'btn btn-primary' %>
    <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
  </div>
</div>